version: "3.8"

services:
    frontend_builder:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: expense_frontend_builder
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - ./frontend_dist_temp:/app/dist
        command: sh -c "npm install && npm run build"
        networks:
            - expense_network_prod

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: expense_backend
        restart: always
        depends_on:
            frontend_builder:
                condition: service_completed_successfully
        volumes:
            - ./frontend_dist_temp:/app/frontend_dist
            - ./staticfiles_build:/app/staticfiles
            - ./media_build:/app/media
        env_file:
            - .env
        expose:
            - "8000"
        networks:
            - expense_network_prod

    nginx:
        build:
            context: ./nginx
            dockerfile: dockerfile

        container_name: expense_nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./staticfiles_build:/app/staticfiles
            - ./media_build:/app/media
        depends_on:
            - backend
        networks:
            - expense_network_prod

networks:
    expense_network_prod:
        external: true
